### ISSUE TITLE
Add support for Vagrantfile.local syntax higlighting

### ISSUE THREAD

**Issue by Graloth** [mastazi/VS-code-vagrantfile#2]
Some vagrant projects rely on also having a Vagrantfile.local, which would have local changes to the default Vagrantfile.
This is very useful when using a pre-built vagrant box for projects, and only want minor changes added.

Please add support for Vagrantfile.local syntax highlighting, it uses the same syntax as the regular Vagrantfile

**Comment by mastazi** [comment]
Thank you for the heads up about the Vagrantfile.local, I didin't know about it. I will look into adding it, it shouldn't be hard.

**Comment by mastazi** [comment]
The change has been published. Sorry for the delay, lately I wasn't well and then I had some deadlines at work. Should you experience any issue with the new version, please let me know.
